default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: B1983ball#
  host: localhost

development:
  <<: *default
  database: my_basecamp2_development

test:
  <<: *default
  database: my_basecamp2_test

production:
  primary: &primary_production
    <<: *default
    database: my_basecamp2_production
    username: my_basecamp2
    password: <%= ENV["MY_BASECAMP2_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: my_basecamp2_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: my_basecamp2_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: my_basecamp2_production_cable
    migrations_paths: db/cable_migrate
